services:
  - type: web
    name: gamercred
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn website.app:app --config gunicorn_config.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RAWG_API_KEY
        sync: false
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_REDIRECT_URI
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"

databases:
  - name: gamercred-db
    databaseName: gamercred
    user: gamercred_user 