services:
  - type: web
    name: gamercred
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn website.app:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: gamercred-db
          property: connectionString
      - key: CORS_ORIGINS
        value: "*"

databases:
  - name: gamercred-db
    databaseName: gamercred
    user: gamercred_user 